name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker BuildKit
      run: |
        echo 'DOCKER_BUILDKIT=1' >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -f tools/Dockerfile --build-arg PYTHON_VERSION=${{ matrix.python-version }} -o . .

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build with Poetry
      run: |
        poetry install --no-dev
        poetry build

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_id: ${{ github.event.release.id }}
        asset_path: ./dist/
        asset_name: "build-${{ matrix.python-version }}.tar.gz"
        asset_content_type: application/gzip
